const ActionTypes = {
  LOAD_DATA: "LOAD_DATA",
  FIND_DATA: "FIND_DATA",
  FIND_LIKE_DATA: "FIND_LIKE_DATA",
  FIND_DATA_HOME: "FIND_DATA_HOME",
  SHOW_CANVAS_FAVORITE: "SHOW_CANVAS_FAVORITE",
  HIDEN_CANVAS_FAVORITE: "HIDEN_CANVAS_FAVORITE",
  SHOW_CANVAS_CART: "SHOW_CANVAS_CART",
  HIDEN_CANVAS_CART: "HIDEN_CANVAS_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: " CLEAR_CART",
};
export default ActionTypes;
